"""remove relation

Revision ID: 7dedb150a36a
Revises: 446cfd3e9c8e
Create Date: 2024-11-06 11:28:03.182619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dedb150a36a'
down_revision: Union[str, None] = '446cfd3e9c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('training_videos_coach_id_fkey', 'training_videos', type_='foreignkey')
    op.drop_column('training_videos', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_videos', sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('training_videos_coach_id_fkey', 'training_videos', 'users', ['coach_id'], ['id'])
    # ### end Alembic commands ###
